name: check-and-test

on:
  - pull_request

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: lint
        run: make lint
      - name: build
        run: make build
      - name: security-check
        run: make security-check
